### PR TITLE
feat: file service

### PR DESCRIPTION
**Pull request by viinxent**
File service using `aws-amplify` storage

### CODE REVIEW

**Comment by xuatz** [comment]
Same like in the auth PR, lets extend this with some basic usage as well.

**Comment by viinxent** [comment]
> Same like in the auth PR, lets extend this with some basic usage as well.

I might, delete this branch and pr the `feat/note-create` as that's where this is heavily used.

**Review by khole — APPROVED** [review]

**Review by khole — APPROVED** [review]
We need to brainstorm as well on the naming convention for the files.

**Comment by viinxent** [comment]
> We need to brainstorm as well on the naming convention for the files.

we could potentially use '.' notation for naming our files base on their purpose exception for components and containers. `*.styles.ts`, `*.sagas.ts`, `*.reducer.ts`, `*.selectors.ts`, `*.service.ts`, `*.util.ts`, `*.lib.ts` and so on..

**Pull request merged**
